// import SONG from './song.json';

// export const getAlbum = () => {
//     const { albumName } = Object.values(SONG.resources.songs)[0].attributes;

//     const releaseDate = Object.values(SONG.resources.albums).find(
//         (album) => album.attributes.name === albumName,
//     )?.attributes.releaseDate;

//     return {
//         band: Object.values(SONG.resources.songs)[0].attributes.artistName,
//         imageSrc: '',
//         album: albumName,
//         releasedAt: `new Date("${releaseDate ?? ''}")`,
//         songs: Object.values(SONG.resources.songs).map(
//             (song) => song.attributes.name,
//         ),
//         link: '',
//     };
// };

// console.log(getAlbum());

export enum Band {
    BLACK_SABBATH = 'Black Sabbath',
    MANOWAR = 'Manowar',
    PANTERA = 'Pantera',
    RAINBOW = 'Rainbow',
    ELF = 'Elf',
    DIO = 'DIO',
    TESTAMENT = 'Testament',
    DAMAGEPLAN = 'Damageplan',
    AC_DC = 'AC/DC',
    SEPULTURA = 'Sepultura',
    KINO = 'Кино',
    ARIA = 'Ария',
    ACCEPT = 'Accept',
    SEKTOR_GAZA = 'Сектор Газа',
    CHERNIY_KOFE = 'Черный кофе',
}

export interface AlbumType {
    band: Band;
    album: string;
    imageSrc: string;
    releasedAt: Date;
    songs?: string[];
    link?: string;
}

const albums: AlbumType[] = [
    {
        band: Band.BLACK_SABBATH,
        album: 'Black Sabbath',
        imageSrc: '/albums/Black-Sabbath_1970_Black-Sabbath.png',
        releasedAt: new Date('1970-02-13'),
        songs: [
            'Black Sabbath',
            'The Wizard',
            'Behind the Wall of Sleep',
            'N.I.B.',
            "Evil Woman (Don't Play Your Games with Me)",
            'Sleeping Village',
            'Warning',
            'Wicked World',
        ],
        link: 'https://music.apple.com/ru/album/black-sabbath-remastered/1438648677',
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Paranoid',
        imageSrc: '/albums/Black-Sabbath_1970_Paranoid.png',
        releasedAt: new Date('1970-09-18'),
        songs: [
            "War Pigs / Luke's Wall",
            'Paranoid',
            'Planet Caravan',
            'Iron Man',
            'Electric Funeral',
            'Hand of Doom',
            'Rat Salad',
            'Jack the Stripper / Fairies Wear Boots',
        ],
        link: 'https://music.apple.com/ru/album/paranoid/1533659667',
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Master of Reality',
        imageSrc: '/albums/Black-Sabbath_1971_Master-of-Reality.png',
        releasedAt: new Date('1971-07-21'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Black Sabbath Vol. 4',
        imageSrc: '/albums/Black-Sabbath_1972_Black-Sabbath-Vol-4.png',
        releasedAt: new Date('1972-09-25'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Sabbath Bloody Sabbath',
        imageSrc: '/albums/Black-Sabbath_1973_Sabbath-Bloody-Sabbath.png',
        releasedAt: new Date('1973-12-01'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Sabotage',
        imageSrc: '/albums/Black-Sabbath_1975_Sabotage.png',
        releasedAt: new Date('1975-07-28'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Technical Ecstasy',
        imageSrc: '/albums/Black-Sabbath_1976_Technical-Ecstasy.png',
        releasedAt: new Date('1976-09-25'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Never Say Die!',
        imageSrc: '/albums/Black-Sabbath_1978_Never-Say-Die.png',
        releasedAt: new Date('1978-09-28'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Heaven & Hell',
        imageSrc: '/albums/Black-Sabbath_1980_Heaven-and-Hell.png',
        releasedAt: new Date('1980-04-25'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Mob Rules',
        imageSrc: '/albums/Black-Sabbath_1981_Mob-Rules.png',
        releasedAt: new Date('1981-11-04'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: 'Dehumanizer',
        imageSrc: '/albums/Black-Sabbath_1992_Dehumanizer.png',
        releasedAt: new Date('1992-06-22'),
    },
    {
        band: Band.BLACK_SABBATH,
        album: '13',
        imageSrc: '/albums/Black-Sabbath_2013_13.png',
        releasedAt: new Date('2013-06-10'),
    },
    {
        band: Band.MANOWAR,
        album: 'Battle Hymns',
        imageSrc: '/albums/Manowar_1982_Battle-Hymns.png',
        releasedAt: new Date('1982-06-07'),
    },
    {
        band: Band.MANOWAR,
        album: 'Into Glory Ride',
        imageSrc: '/albums/Manowar_1983_Into-Glory-Ride.png',
        releasedAt: new Date('1983-07-01'),
    },
    {
        band: Band.MANOWAR,
        album: 'Hail to England',
        imageSrc: '/albums/Manowar_1984_Hail-to-England.png',
        releasedAt: new Date('1984-02-01'),
    },
    {
        band: Band.MANOWAR,
        album: 'Sign of the Hammer',
        imageSrc: '/albums/Manowar_1984_Sign-of-the-Hammer.png',
        releasedAt: new Date('1984-10-15'),
    },
    {
        band: Band.MANOWAR,
        album: 'Fighting the World',
        imageSrc: '/albums/Manowar_1987_Fighting-the-World.png',
        releasedAt: new Date('1987-02-17'),
    },
    {
        band: Band.MANOWAR,
        album: 'Kings of Metal',
        imageSrc: '/albums/Manowar_1988_Kings-of-Metal.png',
        releasedAt: new Date('1988-11-18'),
    },
    {
        band: Band.MANOWAR,
        album: 'The Triumph of Steel',
        imageSrc: '/albums/Manowar_1992_The-Triumph-of-Steel.png',
        releasedAt: new Date('1992-09-29'),
    },
    {
        band: Band.MANOWAR,
        album: 'Louder Than Hell',
        imageSrc: '/albums/Manowar_1996_Louder-Than-Hell.png',
        releasedAt: new Date('1996-04-29'),
    },
    {
        band: Band.MANOWAR,
        album: 'The Dawn of Battle',
        imageSrc: '/albums/Manowar_2002_The-Dawn-of-Battle.png',
        releasedAt: new Date('2002-10-15'),
    },
    {
        band: Band.MANOWAR,
        album: 'Warriors of the World',
        imageSrc: '/albums/Manowar_2002_Warriors-of-the-World.png',
        releasedAt: new Date('2002-06-04'),
    },
    {
        band: Band.MANOWAR,
        album: 'The Sons of Odin',
        imageSrc: '/albums/Manowar_2006_The-Sons-of-Odin.png',
        releasedAt: new Date('2006-06-20'),
    },
    {
        band: Band.MANOWAR,
        album: 'Gods of War',
        imageSrc: '/albums/Manowar_2007_Gods-of-War.png',
        releasedAt: new Date('2007-02-23'),
    },
    {
        band: Band.MANOWAR,
        album: 'Thunder In the Sky',
        imageSrc: '/albums/Manowar_2009_Thunder-In-the-Sky.png',
        releasedAt: new Date('2009-06-13'),
    },
    {
        band: Band.MANOWAR,
        album: 'Battle Hymns',
        imageSrc: '/albums/Manowar_2011_Battle-Hymns.png',
        releasedAt: new Date('2011-11-26'),
    },
    {
        band: Band.MANOWAR,
        album: 'The Lord of Steel',
        imageSrc: '/albums/Manowar_2012_The-Lord-of-Steel.png',
        releasedAt: new Date('2012-06-16'),
    },
    {
        band: Band.MANOWAR,
        album: 'The Lord of Steel (Hammer Edition)',
        imageSrc: '/albums/Manowar_2012_The-Lord-of-Steel-Hammer-Edition.png',
        releasedAt: new Date('2012-06-16'),
    },
    {
        band: Band.MANOWAR,
        album: 'The Final Battle I',
        imageSrc: '/albums/Manowar_2019_The-Final-Battle.png',
        releasedAt: new Date('2019-03-29'),
    },
    {
        band: Band.MANOWAR,
        album: 'Into Glory Ride Imperial Edition MMXIX',
        imageSrc: '/albums/Manowar_2019_Into-Glory-Ride.png',
        releasedAt: new Date('2019-03-29'),
    },
    {
        band: Band.MANOWAR,
        album: 'Hail to England Imperial Edition MMXIX',
        imageSrc: '/albums/Manowar_2019_Hail-to-England.png',
        releasedAt: new Date('2019-03-29'),
    },
    {
        band: Band.MANOWAR,
        album: 'The Revenge of Odysseus (Highlights)',
        imageSrc: '/albums/Manowar_2022_The-Revenge-of-Odysseus.png',
        releasedAt: new Date('2022-06-22'),
    },
    {
        band: Band.MANOWAR,
        album: 'Laut Und Hart Stark Und Schnell',
        imageSrc: '/albums/Manowar_2023_Laut-Und-Hart-Stark-Und-Schnell.png',
        releasedAt: new Date('2023-02-10'),
    },
    {
        band: Band.PANTERA,
        album: 'Cowboys from Hell',
        imageSrc: '/albums/Pantera_1990_Cowboys-from-Hell.png',
        releasedAt: new Date('1990-07-24'),
    },
    {
        band: Band.PANTERA,
        album: 'Vulgar Display of Power',
        imageSrc: '/albums/Pantera_1992_Vulgar-Display-of-Power.png',
        releasedAt: new Date('1992-02-25'),
    },
    {
        band: Band.PANTERA,
        album: 'Far Beyond Driven',
        imageSrc: '/albums/Pantera_1994_Far-Beyond-Driven.png',
        releasedAt: new Date('1994-03-22'),
    },
    {
        band: Band.PANTERA,
        album: 'The Great Southern Trendkill',
        imageSrc: '/albums/Pantera_1996_The-Great-Southern-Trendkill.png',
        releasedAt: new Date('1996-05-07'),
    },
    {
        band: Band.PANTERA,
        album: 'Official Live: 101 Proof',
        imageSrc: '/albums/Pantera_1997_101-Proof.png',
        releasedAt: new Date('1997-07-14'),
    },
    {
        band: Band.PANTERA,
        album: 'Reinventing the Steel',
        imageSrc: '/albums/Pantera_2000_Reinventing-the-Steel.png',
        releasedAt: new Date('2000-03-21'),
    },
    {
        band: Band.RAINBOW,
        album: "Ritchie Blackmore's Rainbow",
        imageSrc: '/albums/Rainbow_1975_Ritchie-Blackmores-Rainbow.png',
        releasedAt: new Date('1975-05-17'),
    },
    {
        band: Band.RAINBOW,
        album: 'Rising',
        imageSrc: '/albums/Rainbow_1976_Rising.png',
        releasedAt: new Date('1976-05-15'),
    },
    {
        band: Band.RAINBOW,
        album: "Long Live Rock 'n' Roll",
        imageSrc: '/albums/Rainbow_1978_Long-Live-Rock-N-Roll.png',
        releasedAt: new Date('1978-04-09'),
    },
    {
        band: Band.ELF,
        album: 'Elf',
        imageSrc: '/albums/Elf_1972_Elf.png',
        releasedAt: new Date('1972-08-15'),
    },
    {
        band: Band.ELF,
        album: 'Carolina County Ball',
        imageSrc: '/albums/Elf_1974_Carolina-County-Ball.png',
        releasedAt: new Date('1974-04-15'),
    },
    {
        band: Band.ELF,
        album: 'Trying to Burn the Sun',
        imageSrc: '/albums/Elf_1975_Trying-to-Burn-the-Sun.png',
        releasedAt: new Date('1975-06-01'),
    },
    {
        band: Band.DIO,
        album: 'Holy Diver',
        imageSrc: '/albums/Dio_1983_Holy-Diver.png',
        releasedAt: new Date('1983-05-25'),
        link: 'https://music.apple.com/ru/album/holy-diver-remastered/1440757603',
        songs: [
            'Stand Up and Shout',
            'Holy Diver',
            'Gypsy',
            'Caught In the Middle',
            "Don't Talk to Strangers",
            'Straight Through the Heart',
            'Invisible',
            'Rainbow In the Dark',
            'Shame On the Night',
        ],
    },
    {
        band: Band.TESTAMENT,
        album: 'Titans of Creation',
        imageSrc: '/albums/Testament_2020_Titans-of-Creation.png',
        releasedAt: new Date('2020-04-03'),
        link: 'https://music.apple.com/ru/album/titans-of-creation/1493544060',
        songs: [
            'Children of the Next Level',
            'WWIII',
            'Dream Deceiver',
            'Night of the Witch',
            'City of Angels',
            "Ishtar's Gate",
            'Symptoms',
            'False Prophet',
            'The Healers',
            'Code of Hammurabi',
            'Curse of Osiris',
            'Catacombs',
        ],
    },
    {
        band: Band.TESTAMENT,
        album: 'The Legacy',
        imageSrc: '/albums/Testament_1987_The-Legacy.png',
        releasedAt: new Date('1987-04-21'),
        link: 'https://music.apple.com/ru/album/the-legacy/301027622',
        songs: [
            'Over the Wall',
            'The Haunting',
            'Burnt Offerings',
            'Raging Waters',
            'Curse of the Legions of Death',
            'First Strike Is Deadly',
            'Do or Die',
            'Alone In the Dark',
            'Apocalyptic City',
        ],
    },
    {
        band: Band.TESTAMENT,
        album: 'The New Order',
        imageSrc: '/albums/Testament_1988_The-New-Order.png',
        releasedAt: new Date('1988-05-05'),
        link: 'https://music.apple.com/ru/album/the-new-order/301007896',
        songs: [
            'Eerie Inhabitants',
            'The New Order',
            'Trial By Fire',
            'Into the Pit',
            'Hypnosis',
            'Disciples of the Watch',
            'The Preacher',
            "Nobody's Fault",
            'A Day of Reckoning',
            'Musical Death (A Dirge)',
        ],
    },
    {
        band: Band.DAMAGEPLAN,
        album: 'New Found Power',
        imageSrc: '/albums/Damageplan_2004_New-Found-Power.png',
        releasedAt: new Date('2004-02-10'),
        link: 'https://music.apple.com/ru/album/new-found-power/5356931',
    },
    {
        band: Band.AC_DC,
        album: 'High Voltage',
        imageSrc: '/albums/AC-DC_1976_High-Voltage.png',
        releasedAt: new Date('1976-04-30'),
        link: 'https://music.apple.com/ru/album/high-voltage/574124734',
        songs: [
            "It's a Long Way to the Top (If You Wanna Rock 'N' Roll)",
            "Rock 'N' Roll Singer",
            'The Jack',
            'Live Wire',
            'T.N.T.',
            'Can I Sit Next to You Girl',
            'Little Lover',
            "She's Got Balls",
            'High Voltage',
        ],
    },
    {
        band: Band.SEPULTURA,
        album: 'Arise',
        imageSrc: '/albums/Sepultura_1991_Arise.png',
        releasedAt: new Date('1991-04-02'),
        link: 'https://music.apple.com/ru/album/arise-remastered/1392358661',
        songs: [
            'Arise',
            'Dead Embryonic Cells',
            'Desperate Cry',
            'Murder',
            'Subtraction',
            'Altered State',
            'Under Siege (Regnum Irae)',
            'Meaningless Movements',
            'Infected Voice',
            'Orgasmatron',
            'Intro (Arise)',
            'C.I.U. (Criminals In Uniform)',
        ],
    },
    {
        band: Band.KINO,
        album: '45',
        imageSrc: '/albums/Kino_1982_45.png',
        releasedAt: new Date('1982-07-29'),
        link: 'https://music.apple.com/ru/album/45/1374383220',
        songs: [
            'Время есть, а денег нет',
            'Просто хочешь ты знать',
            'Алюминиевые огурцы',
            'Солнечные дни',
            'Бездельник №1',
            'Бездельник №2',
            'Электричка',
            'Восьмиклассница',
            'Мои друзья...',
            'Ситар играл',
            'Дерево',
            'Когда-то ты был битником',
            'На кухне',
            'Асфальт',
        ],
    },
    {
        band: Band.KINO,
        album: '46',
        imageSrc: '/albums/Kino_1983_46.png',
        releasedAt: new Date('1983-01-22'),
        link: 'https://music.apple.com/ru/album/46/1374373066',
        songs: [
            'Троллейбус',
            'Камчатка',
            'Транквилизатор',
            'Я иду по улице',
            'Дождь для нас',
            'Пора',
            'Каждую ночь',
            'Без десяти',
            'Музыка волн',
            'Саша',
            'Хочу быть с тобой',
            'Генерал',
            'Стань птицей',
            'Сельва',
            'Я хочу быть кочегаром',
        ],
    },
    {
        band: Band.KINO,
        album: 'Начальник камчатки',
        imageSrc: '/albums/Kino_1984_The-head-of-Kamchatka.png',
        releasedAt: new Date('1984-06-23'),
        link: 'https://music.apple.com/ru/album/начальник-камчатки/1333012776',
        songs: [
            'Последний герой',
            'Каждую ночь',
            'Транквилизатор',
            'Сюжет для новой песни',
            'Гость',
            'Камчатка',
            'Ария Мистера Х (Из оперетты Имре Кальмана "Принцесса Цирка")',
            'Троллейбус',
            'Растопите снег',
            'Дождь для нас',
            'Хочу быть с тобой',
            'Генерал',
            'Прогулка романтика',
            'Танкисты',
            'Анаша',
            'Постой, паровоз',
        ],
    },
    {
        band: Band.ARIA,
        album: 'Мания величия',
        imageSrc: '/albums/Aria_1985_Мания-величия.png',
        releasedAt: new Date('1985-10-31'),
        link: 'https://music.apple.com/ru/album/мания-величия/819705886',
        songs: [
            'Это рок',
            'Тореро',
            'Волонтёр',
            'Бивни чёрных скал',
            'Мания величия',
            'Жизнь задаром',
            'Мечты',
            'Позади Америка',
        ],
    },
    {
        band: Band.ARIA,
        album: 'С кем ты?',
        imageSrc: '/albums/Aria_1986_С-кем-ты.png',
        releasedAt: new Date('1986-12-31'),
        link: 'https://music.apple.com/ru/album/с-кем-ты/819701693',
        songs: [
            'Воля и разум',
            'Встань, страх преодолей',
            'Здесь куют металл',
            'С кем ты?',
            'Без тебя',
            'Память о...',
            'Икар',
            'Игры не для нас',
        ],
    },
    {
        band: Band.ACCEPT,
        album: 'Breaker',
        imageSrc: '/albums/Accept_1981_Breaker.png',
        releasedAt: new Date('1981-03-16'),
        link: 'https://music.apple.com/ru/album/breaker/1705761372',
        songs: [
            'Starlight',
            'Breaker',
            'Run If You Can',
            "Can't Stand The Night",
            'Son Of A Bitch',
            'Burning',
            'Feelings',
            'Midnight Highway',
            'Breaking Up Again',
            'Down And Out',
        ],
    },
    {
        band: Band.SEKTOR_GAZA,
        album: 'Ядрена Вошь',
        imageSrc: '/albums/Sektor-gaza_1990_Ядрена-Вошь.png',
        releasedAt: new Date('1990-05-27'),
        link: 'https://music.apple.com/ru/album/ядрёна-вошь/583062127',
        songs: [
            'Мы - совковые ребята',
            'Скотник',
            'Носки',
            'Импотент',
            'Ядрёна вошь',
            'Мент',
            'Колыбельная',
            'План',
            'Спор',
            'Караван',
            'Пердун',
            'Вечером на лавочке',
            'Возле дома твоего',
            'Минет',
        ],
    },
    {
        band: Band.AC_DC,
        album: 'Dirty Deeds Done Dirt Cheap',
        imageSrc: '/albums/AC-DC_1976_Dirty-Deeds-Done-Dirt-Cheap.png',
        releasedAt: new Date('1976-09-20'),
        link: 'https://music.apple.com/ru/album/dirty-deeds-done-dirt-cheap/575306275',
        songs: [
            'Dirty Deeds Done Dirt Cheap',
            'Love at First Feel',
            'Big Balls',
            'Rocker',
            'Problem Child',
            "There's Gonna Be Some Rockin'",
            "Ain't No Fun (Waiting Round to Be a Millionaire)",
            'Ride On',
            'Squealer',
        ],
    },
    {
        band: Band.AC_DC,
        album: 'Let There Be Rock',
        imageSrc: '/albums/AC-DC_1977_Let-There-Be-Rock.png',
        releasedAt: new Date('1977-03-21'),
        link: 'https://music.apple.com/ru/album/let-there-be-rock/574124483',
        songs: [
            'Go Down',
            'Dog Eat Dog',
            'Let There Be Rock',
            'Bad Boy Boogie',
            'Problem Child',
            'Overdose',
            "Hell Ain't a Bad Place to Be",
            'Whole Lotta Rosie',
        ],
    },
    {
        band: Band.AC_DC,
        album: 'Powerage',
        imageSrc: '/albums/AC-DC_1978_Powerage.png',
        releasedAt: new Date('1978-05-05'),
        link: 'https://music.apple.com/ru/album/powerage/574050248',
        songs: [
            "Rock 'N' Roll Damnation",
            'Down Payment Blues',
            'Gimme a Bullet',
            'Riff Raff',
            'Sin City',
            "What's Next to the Moon",
            "Gone Shootin'",
            'Up to My Neck In You',
            'Kicked In the Teeth',
        ],
    },
    {
        band: Band.AC_DC,
        album: 'Highway to Hell',
        imageSrc: '/albums/AC-DC_1979_Highway-to-Hell.png',
        releasedAt: new Date('1979-07-27'),
        link: 'https://music.apple.com/ru/album/highway-to-hell/574043989',
        songs: [
            'Highway to Hell',
            'Girls Got Rhythm',
            'Walk All Over You',
            'Touch Too Much',
            'Beating Around the Bush',
            'Shot Down In Flames',
            'Get It Hot',
            "If You Want Blood (You've Got It)",
            'Love Hungry Man',
            'Night Prowler',
        ],
    },
    {
        band: Band.AC_DC,
        album: 'Back In Black',
        imageSrc: '/albums/AC-DC_1980_Back-In-Black.png',
        releasedAt: new Date('1980-07-25'),
        link: 'https://music.apple.com/ru/album/back-in-black/574050396',
        songs: [
            'Hells Bells',
            'Shoot to Thrill',
            'What Do You Do for Money Honey',
            'Givin the Dog a Bone',
            'Let Me Put My Love Into You',
            'Back In Black',
            'You Shook Me All Night Long',
            'Have a Drink On Me',
            'Shake a Leg',
            "Rock and Roll Ain't Noise Pollution",
        ],
    },
    {
        band: Band.AC_DC,
        album: 'For Those About to Rock (We Salute You)',
        imageSrc: '/albums/AC-DC_1981_For-Those-About-to-Rock.png',
        releasedAt: new Date('1981-11-20'),
        link: 'https://music.apple.com/ru/album/for-those-about-to-rock-we-salute-you/574055123',
        songs: [
            'For Those About to Rock (We Salute You)',
            'Put the Finger On You',
            "Let's Get It Up",
            'Inject the Venom',
            'Snowballed',
            'Evil Walks',
            'C.O.D.',
            'Breaking the Rules',
            'Night of the Long Knives',
            'Spellbound',
        ],
    },
    {
        band: Band.AC_DC,
        album: 'Flick of the Switch',
        imageSrc: '/albums/AC-DC_1983_Flick-of-the-Switch.png',
        releasedAt: new Date('1983-08-15'),
        link: 'https://music.apple.com/ru/album/flick-of-the-switch/574053085',
        songs: [
            'Rising Power',
            'This House Is On Fire',
            'Flick of the Switch',
            'Nervous Shakedown',
            'Landslide',
            'Guns for Hire',
            'Deep In the Hole',
            'Bedlam In Belgium',
            'Badlands',
            'Brain Shake',
        ],
    },
    {
        band: Band.AC_DC,
        album: 'Fly On the Wall',
        imageSrc: '/albums/AC-DC_1985_Fly-On-the-Wall.png',
        releasedAt: new Date('1985-06-28'),
        songs: [
            'Fly On the Wall',
            'Shake Your Foundations',
            'First Blood',
            'Danger',
            'Sink the Pink',
            'Playing with Girls',
            'Stand Up',
            'Hell or High Water',
            'Back In Business',
            'Send for the Man',
        ],
        link: 'https://music.apple.com/ru/album/fly-on-the-wall/574051054',
    },
    {
        band: Band.AC_DC,
        album: 'Blow Up Your Video',
        imageSrc: '/albums/AC-DC_1988_Blow-Up-Your-Video.png',
        releasedAt: new Date('1988-01-18'),
        songs: [
            'Heatseeker',
            "That's the Way I Wanna Rock 'N' Roll",
            'Meanstreak',
            'Go Zone',
            "Kissin' Dynamite",
            'Nick of Time',
            "Some Sin for Nuthin'",
            'Ruff Stuff',
            "Two's Up",
            'This Means War',
        ],
        link: 'https://music.apple.com/ru/album/blow-up-your-video/574051075',
    },
    {
        band: Band.AC_DC,
        album: 'The Razors Edge',
        imageSrc: '/albums/AC-DC_1990_The-Razors-Edge.png',
        releasedAt: new Date('1990-09-21'),
        songs: [
            'Thunderstruck',
            'Fire Your Guns',
            'Moneytalks',
            'The Razors Edge',
            'Mistress for Christmas',
            'Rock Your Heart Out',
            'Are You Ready',
            'Got You by the Balls',
            'Shot of Love',
            "Let's Make It",
            'Goodbye and Good Riddance to Bad Luck',
            'If You Dare',
        ],
        link: 'https://music.apple.com/ru/album/the-razors-edge/574049507',
    },
    {
        band: Band.AC_DC,
        album: 'Ballbreaker',
        imageSrc: '/albums/AC-DC_1995_Ballbreaker.png',
        releasedAt: new Date('1995-09-26'),
        songs: [
            'Hard As a Rock',
            'Cover You In Oil',
            'The Furor',
            'Boogie Man',
            'The Honey Roll',
            "Burnin' Alive",
            'Hail Caesar',
            'Love Bomb',
            'Caught with Your Pants Down',
            'Whiskey On the Rocks',
            'Ballbreaker',
        ],
        link: 'https://music.apple.com/ru/album/ballbreaker/574049508',
    },
    {
        band: Band.AC_DC,
        album: 'Stiff Upper Lip',
        imageSrc: '/albums/AC-DC_2000_Stiff-Upper-Lip.png',
        releasedAt: new Date('2000-02-28'),
        songs: [
            'Stiff Upper Lip',
            'Meltdown',
            'House of Jazz',
            'Hold Me Back',
            'Safe In New York City',
            "Can't Stand Still",
            "Can't Stop Rock 'N' Roll",
            'Satellite Blues',
            'Damned',
            'Come and Get It',
            'All Screwed Up',
            'Give It Up',
        ],
        link: 'https://music.apple.com/ru/album/stiff-upper-lip/574051604',
    },
    {
        band: Band.AC_DC,
        album: 'Black Ice',
        imageSrc: '/albums/AC-DC_2008_Black-Ice.png',
        releasedAt: new Date('2008-10-20'),
        songs: [
            "Rock 'N' Roll Train",
            'Skies On Fire',
            'Big Jack',
            'Anything Goes',
            'War Machine',
            "Smash 'N' Grab",
            "Spoilin' for a Fight",
            'Wheels',
            'Decibel',
            'Stormy May Day',
            "She Likes Rock 'N' Roll",
            'Money Made',
            "Rock 'N' Roll Dream",
            'Rocking All the Way',
            'Black Ice',
        ],
        link: 'https://music.apple.com/ru/album/black-ice/574052242',
    },
    {
        band: Band.AC_DC,
        album: 'Rock or Bust',
        imageSrc: '/albums/AC-DC_2014_Rock-or-Bust.png',
        releasedAt: new Date('2014-11-28'),
        songs: [
            'Rock or Bust',
            'Play Ball',
            'Rock the Blues Away',
            'Miss Adventure',
            'Dogs of War',
            'Got Some Rock & Roll Thunder',
            'Hard Times',
            'Baptism By Fire',
            'Rock the House',
            'Sweet Candy',
            'Emission Control',
        ],
        link: 'https://music.apple.com/ru/album/rock-or-bust/923586222',
    },
    {
        band: Band.AC_DC,
        album: 'POWER UP',
        imageSrc: '/albums/AC-DC_2020_Power-Up.png',
        releasedAt: new Date('2020-11-13'),
        songs: [
            'Realize',
            'Rejection',
            'Shot in the Dark',
            'Through The Mists Of Time',
            "Kick You When You're Down",
            "Witch's Spell",
            'Demon Fire',
            'Wild Reputation',
            "No Man's Land",
            'Systems Down',
            'Money Shot',
            'Code Red',
        ],
        link: 'https://music.apple.com/ru/album/power-up/1533816185',
    },
    {
        band: Band.AC_DC,
        album: 'Who Made Who',
        imageSrc: '/albums/AC-DC_1986_Who-Made-Who.png',
        releasedAt: new Date('1986-05-24'),
        songs: [
            'Who Made Who',
            'You Shook Me All Night Long',
            'D.T.',
            'Sink the Pink',
            'Ride On',
            'Hells Bells',
            'Shake Your Foundations',
            'Chase the Ace',
            'For Those About to Rock (We Salute You)',
        ],
        link: 'https://music.apple.com/ru/album/who-made-who/575988907',
    },
    {
        band: Band.AC_DC,
        album: 'Backtracks',
        imageSrc: '/albums/AC-DC_2009_Backtracks.png',
        releasedAt: new Date('2009-11-06'),
        songs: [
            'High Voltage (Original Australian Release)',
            'Stick Around',
            'Love Song',
            "It's a Long Way to the Top (If You Wanna Rock 'N' Roll) [Original Australian Release]",
            'Rocker (Original Australian Release)',
            'Fling Thing',
            'Dirty Deeds Done Dirt Cheap (Original Australian Release)',
            "Ain't No Fun (Waiting Round to Be a Millionaire) [Original Australian Release]",
            'R.I.P. (Rock In Peace)',
            'Carry Me Home',
            'Crabsody In Blue',
            'Cold Hearted Man',
            'Who Made Who (12" Extended Mix)',
            'Snake Eye',
            'Borrowed Time',
            'Down On the Borderline',
            'Big Gun',
            'Cyberspace',
            'Dirty Deeds Done Dirt Cheap (Live Sydney Festival, Jan. 30, 1977)',
            'Dog Eat Dog (Live Apollo Theatre, Glasgow, Apr. 30, 1978)',
            'Live Wire (Live Hammersmith Odeon, London, Nov. 2, 1979)',
            'Shot Down In Flames (Live Hammersmith Odeon, London, Nov. 2, 1979)',
            'Back In Black (Live Capital Center, Landover MD, Dec. 21, 1981)',
            'T.N.T. (Live Capital Center, Landover MD, Dec. 21, 1981)',
            'Let There Be Rock (Live Capital Center, Landover MD, Dec. 21, 1981)',
            'Guns for Hire (Live Joe Louis Arena, Detroit MI, Nov. 18, 1983)',
            'Sin City (Live Joe Louis Arena, Detroit MI, Nov. 18, 1983)',
            "Rock and Roll Ain't Noise Pollution (Live Joe Louis Arena, Detroit MI, Nov. 18, 1983)",
            'This House Is On Fire (Live Joe Louis Arena, Detroit MI, Nov. 18, 1983)',
            'You Shook Me All Night Long (Live Joe Louis Arena, Detroit MI, Nov. 18, 1983)',
            'Jailbreak (Live Dallas TX, Oct. 12, 1985)',
            'Shoot to Thrill (Live Donington Park, Aug. 17, 1991)',
            "Hell Ain't a Bad Place to Be (Live Donington Park, Aug. 17, 1991)",
            'High Voltage (Live)',
            'Hells Bells (Live Donington Park, Aug. 17, 1991)',
            'Whole Lotta Rosie (Live Donington Park, Aug. 17, 1991)',
            'Dirty Deeds Done Dirt Cheap (Live)',
            'Highway to Hell (Live Tushino Airfield, Moscow, Sept. 28, 1991)',
            'Back In Black (Live Tushino Airfield, Moscow, Sept. 28, 1991)',
            'For Those About to Rock (We Salute You) [Live Tushino Airfield, Moscow, Sept. 28, 1991]',
            'Ballbreaker (Live Plaza De Toros De Las Ventas, Madrid, July, 10, 1996)',
            'Hard As a Rock (Live Plaza De Toros De Las Ventas, Madrid, July, 10, 1996)',
            'Dog Eat Dog (Live Plaza De Toros De Las Ventas, Madrid, July, 10, 1996)',
            'Hail Caesar (Live Plaza De Toros De Las Ventas, Madrid, July, 10, 1996)',
            'Whole Lotta Rosie (Live Plaza De Toros De Las Ventas, Madrid, July, 10, 1996)',
            'You Shook Me All Night Long (Live Plaza De Toros De Las Ventas, Madrid, July, 10, 1996)',
            'Safe In New York City (Live Phoenix AZ, Sept. 13, 2000)',
        ],
        link: 'https://music.apple.com/ru/album/backtracks-deluxe-edition/576003045',
    },
    {
        band: Band.KINO,
        album: 'Это не любовь',
        imageSrc: '/albums/Kino_1985_Это-не-любовь.png',
        releasedAt: new Date('1985-01-01'),
        songs: [
            'Прохожий',
            'Стишок',
            'Саша',
            'Рядом со мной',
            'Музыка волн',
            'Я объявляю свой дом',
            'Разреши мне...',
            'Весна',
            'Уходи',
            'Верь мне',
            'Дети проходных дворов',
            'Проснись',
            'Город',
            'Это не любовь',
        ],
        link: 'https://music.apple.com/ru/album/это-не-любовь/1333013856',
    },
    {
        band: Band.KINO,
        album: 'Ночь',
        imageSrc: '/albums/Kino_1986_Ночь.png',
        releasedAt: new Date('1986-01-01'),
        songs: [
            'Закрой за мной дверь, я ухожу',
            'Жизнь в стёклах',
            'Танец',
            'Мы хотим танцевать',
            'Мама-анархия',
            'Фильмы',
            'Ночь',
            'Твой номер',
            'Спокойная ночь',
            'Последний герой',
            'Дальше действовать будем мы',
            'Игра',
            'Видели ночь',
            'Попробуй спеть вместе со мной',
            'Звёзды останутся здесь',
        ],
        link: 'https://music.apple.com/ru/album/ночь/1333016089',
    },
    {
        band: Band.KINO,
        album: 'Группа крови',
        imageSrc: '/albums/Kino_1988_Группа-крови.png',
        releasedAt: new Date('1988-01-01'),
        songs: [
            'Закрой за мной дверь, я ухожу',
            'Спокойная ночь',
            'Бошетунмай',
            'Попробуй спеть вместе со мной',
            'Прохожий',
            'Дальше действовать будем мы',
            'Группа крови',
            'Легенда',
            'Война',
            'В наших глазах',
            'Мама, мы все сошли с ума',
        ],
        link: 'https://music.apple.com/ru/album/группа-крови/1333010977',
    },
    {
        band: Band.KINO,
        album: 'Последний герой',
        imageSrc: '/albums/Kino_1989_Последний-герой.png',
        releasedAt: new Date('1989-01-01'),
        songs: [
            'Хочу перемен',
            'Последний герой',
            'Группа крови',
            'В наших глазах',
            'Мама, мы все тяжело больны',
            'Война',
            'Спокойная ночь',
            'Электричка',
            'Троллейбус',
            'Печаль',
        ],
        link: 'https://music.apple.com/ru/album/последний-герой/1333009843',
    },
    {
        band: Band.KINO,
        album: 'Звезда по имени Солнце',
        imageSrc: '/albums/Kino_1989_Звезда-по-имени-Солнце.png',
        releasedAt: new Date('1989-01-01'),
        songs: [
            'Стук (Одно лишь слово)',
            'Пачка сигарет',
            'Место для шага вперёд',
            'Звезда по имени Солнце',
            'Песня без слов',
            'Апрель',
            'Печаль',
            'Невесёлая песня',
            'Сказка',
        ],
        link: 'https://music.apple.com/ru/album/звезда-по-имени-солнце/1333017666',
    },
    {
        band: Band.KINO,
        album: 'Чёрный альбом',
        imageSrc: '/albums/Kino_1990_Чёрный-альбом.png',
        releasedAt: new Date('1990-01-01'),
        songs: [
            'Звезда',
            'Кукушка',
            'Нам с тобой',
            'Следи за собой',
            'Муравейник',
            'Завтра война',
            'Лето',
            'Когда твоя девушка больна',
            'Сосны на морском берегу',
            'Красно-жёлтые дни',
        ],
        link: 'https://music.apple.com/ru/album/чёрный-альбом/1333012313',
    },
    {
        band: Band.SEPULTURA,
        album: 'Morbid Visions / Bestial Devastation',
        imageSrc: '/albums/Sepultura_1986_Morbid-Visions.png',
        releasedAt: new Date('1986-01-01'),
        songs: [
            'Morbid Visions',
            'Mayhem',
            'Troops of Doom',
            'War',
            'Crucifixion',
            'Show Me the Wrath',
            'Funeral Rites',
            'Empire of the Damned',
            'The Curse',
            'Bestial Devastation',
            'Antichrist',
            'Necromancer',
            'Warriors of Death',
            'Necromancer (Demo)',
            'Anticop (Live)',
        ],
        link: 'https://music.apple.com/ru/album/morbid-visions-bestial-devastation/214374522',
    },
    {
        band: Band.SEPULTURA,
        album: 'Schizophrenia',
        imageSrc: '/albums/Sepultura_1987_Schizophrenia.png',
        releasedAt: new Date('1987-10-30'),
        songs: [
            'Intro (Schizophrenia)',
            'From the Past Comes the Storms',
            'To the Wall',
            'Escape to the Void',
            'Inquisition Symphony',
            'Screams Behind the Shadows',
            'Septic Schizo',
            'The Abyss',
            'R.I.P. (Rest In Pain)',
            'Troops of Doom',
            'The Past Reborns the Storms (Demo)',
            'Septic Schizo (Rough Mix)',
            'To the Wall (Rough Mix)',
        ],
        link: 'https://music.apple.com/ru/album/schizophrenia/214474048',
    },
    {
        imageSrc: '/albums/Sepultura_1989_Beneath-the-Remains.png',
        band: Band.SEPULTURA,
        album: 'Beneath the Remains',
        releasedAt: new Date('1989-04-07'),
        songs: [
            'Beneath the Remains',
            'Inner Self',
            'Stronger Than Hate',
            'Mass Hypnosis',
            'Sarcastic Existence',
            'Slaves of Pain',
            'Lobotomy',
            'Hungry',
            'Primitive Future',
            'A Hora e a Vez do Cabelo Nascer',
            'Inner Self (Drum Tracks, Scratch Guitar, No Bass, No Vox)',
            'Mass Hypnosis (Drum Tracks, Scratch Guitar, No Bass, No Vox)',
        ],
        link: 'https://music.apple.com/ru/album/beneath-the-remains/214411044',
    },
    {
        band: Band.SEPULTURA,
        imageSrc: '/albums/Sepultura_1993_Chaos-A.D..png',
        album: 'Chaos A.D.',
        releasedAt: new Date('1993-09-01'),
        songs: [
            'Refuse / Resist',
            'Territory',
            'Slave New World',
            'Amen',
            'Kaiowas',
            'Propaganda',
            'Biotech Is Godzilla',
            'Nomad',
            'We Who Are Not As Others',
            'Manifest',
            'The Hunt',
            'Clenched Fist',
        ],
        link: 'https://music.apple.com/ru/album/chaos-a-d-remastered/1291413726',
    },
    {
        band: Band.SEPULTURA,
        imageSrc: '/albums/Sepultura_1996_Roots.png',
        album: 'Roots',
        releasedAt: new Date('1996-02-20'),
        songs: [
            'Roots Bloody Roots',
            'Attitude',
            'Cut-Throat',
            'Ratamahatta',
            'Breed Apart',
            'Straighthate',
            'Spit',
            'Lookaway',
            'Dusted',
            'Born Stubborn',
            'Jasco',
            'Itsári',
            'Ambush',
            'Endangered Species',
            'Dictatorshit',
            'Canyon Jam',
        ],
        link: 'https://music.apple.com/ru/album/roots-remastered/1299151419',
    },
    {
        band: Band.ARIA,
        imageSrc: '/albums/Aria_1987_Герой-асфальта.png',
        album: 'Герой асфальта',
        releasedAt: new Date('1987-01-01'),
        songs: [
            'На службе силы зла',
            'Герой асфальта',
            'Мёртвая зона',
            '1100',
            'Улица роз',
            'Баллада о древнерусском воине',
        ],
        link: 'https://music.apple.com/ru/album/герой-асфальта/819711321',
    },
    {
        band: Band.ARIA,
        imageSrc: '/albums/Aria_1989_Игра-с-огнём.png',
        album: 'Игра с огнём',
        releasedAt: new Date('1989-03-01'),
        songs: [
            'Что вы сделали с вашей мечтой',
            'Раскачаем этот мир',
            'Раб страха',
            'Искушение',
            'Игра с огнём',
            'Бой продолжается',
            'Дай жару',
        ],
        link: 'https://music.apple.com/ru/album/игра-с-огнём/823727181',
    },
    {
        band: Band.ARIA,
        imageSrc: '/albums/Aria_1991_Кровь-за-кровь.png',
        album: 'Кровь за кровь',
        releasedAt: new Date('1991-01-01'),
        songs: [
            'Прощай, Норфолк!',
            'Зомби',
            'Антихрист',
            'Не хочешь - не верь мне',
            'Кровь за кровь',
            'Бесы',
            'Всё, что было',
            'Следуй за мной',
        ],
        link: 'https://music.apple.com/ru/album/кровь-за-кровь/819720980',
    },
    {
        band: Band.ARIA,
        imageSrc: '/albums/Aria_1995_Ночь-короче-дня.png',
        album: 'Ночь короче дня',
        releasedAt: new Date('1995-09-11'),
        songs: [
            'Рабство иллюзий',
            'Паранойя',
            'Ангельская пыль',
            'Уходи и не возвращайся!',
            'Король дороги',
            'Возьми моё сердце',
            'Зверь',
            'Дух войны',
            'Ночь короче дня',
        ],
        link: 'https://music.apple.com/ru/album/ночь-короче-дня/824645472',
    },
    {
        band: Band.ARIA,
        imageSrc: '/albums/Aria_1998_Генератор-зла.png',
        album: 'Генератор зла',
        releasedAt: new Date('1998-05-02'),
        songs: [
            'Смотри!',
            'Грязь',
            'Дезертир',
            'Пытка тишиной',
            'Беги за солнцем',
            'Обман',
            'Отшельник',
            'Закат',
            'Дьявольский зной',
            'Замкнутый круг',
        ],
        link: 'https://music.apple.com/ru/album/генератор-зла/819719967',
    },
    {
        band: Band.ARIA,
        imageSrc: '/albums/Aria_2001_Химера.png',
        album: 'Химера',
        releasedAt: new Date('2001-04-12'),
        songs: [
            'Химера',
            'Небо тебя найдёт',
            'Я не сошёл с ума',
            'Вампир',
            'Горящая стрела',
            'Штиль',
            'Путь в Никуда',
            'Ворон',
            'Осколок льда',
            'Тебе дадут знак',
        ],
        link: 'https://music.apple.com/ru/album/химера/646971999',
    },
    {
        band: Band.CHERNIY_KOFE,
        imageSrc: '/albums/Cherniy-kofe_1986_Светлый-металл.png',
        album: 'Светлый металл',
        releasedAt: new Date('1986-01-01'),
        songs: [
            'Это - рок',
            'Дьявол во плоти',
            'Путешествие в жизнь',
            'Светлый металл',
            'Света луч',
            'Звёздный водоём',
            'Владимирская Русь',
            'Знамя мира',
            'Страна',
            'Переступи порог',
            'Звуки космоса',
            'Чёрный кофе',
            'Из придорожной тени',
        ],
        link: 'https://music.apple.com/ru/album/светлый-металл/1442595511',
    },
    {
        band: Band.CHERNIY_KOFE,
        imageSrc: '/albums/Cherniy-kofe_1987_Переступи-порог.png',
        album: 'Переступи порог',
        releasedAt: new Date('1987-12-03'),
        songs: [
            'Переступи порог',
            'Владимирская Русь',
            'Жизни рассвет',
            'Листья',
            'Мой дом',
            'Звёздный водоём',
            'Пылает за окном звезда',
            'Незнакомец',
            'Чёрный кофе',
            'Зимний портрет',
            'Светлый металл',
            'Знамя мира',
        ],
        link: 'https://music.apple.com/ru/album/переступи-порог/1442744097',
    },
    {
        band: Band.CHERNIY_KOFE,
        imageSrc: '/albums/Cherniy-kofe_1990_Вольному-воля.png',
        album: 'Вольному воля',
        releasedAt: new Date('1990-06-01'),
        songs: [
            'Брожу по городу один',
            'Вольному воля',
            'Ночь',
            'Светлый образ',
            'И только мы',
            'После тебя',
            'Ностальгия',
            'Это - рок',
            'Звуки космоса',
            'Из придорожной тени',
        ],
        link: 'https://music.apple.com/ru/album/вольному-воля/1439262884',
    },
    {
        band: Band.CHERNIY_KOFE,
        imageSrc: '/albums/Cherniy-kofe_1992_Леди-осень.png',
        album: 'Леди осень',
        releasedAt: new Date('1992-06-01'),
        songs: [
            'Где ответ',
            'Леди осень',
            'Зимний портрет',
            'Shaking Baby',
            'Холодный дом',
            "Don't Ask Me Baby",
            'Владимирская Русь',
            'Вольному воля',
            'Кода',
            'Во плоти',
            'Светлый металл',
            'Wandering Souls',
        ],
        link: 'https://music.apple.com/ru/album/леди-осень/1438144293',
    },
    {
        band: Band.CHERNIY_KOFE,
        imageSrc: '/albums/Cherniy-kofe_2004_Они-бесы.png',
        album: 'Они бесы',
        releasedAt: new Date('2004-06-01'),
        songs: [
            'Про рок',
            'Поёт любовь',
            'Церквушки',
            'Они бесы',
            'Когда-нибудь',
            'Яблочный спас',
            'Всё как прежде',
            'Радуга',
            'Ты молот',
            'Время',
        ],
        link: 'https://music.apple.com/ru/album/они-бесы/1448296990',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_1997_Сектор-Газа.png',
        album: 'Сектор Газа',
        releasedAt: new Date('1997-12-01'),
        songs: [
            'Сектор Газа',
            'Ангел Секса',
            'Авто-Мат',
            'Я Мочился В Ночь',
            'Эстрадная песня',
            'Аборт или роды',
            'Самогонщики',
            'Спокойной Ночи, Малыши',
            'Я - Мразь',
            'Сумасшедший Труп',
            'Подкуп',
            'Дураки',
            'Война',
        ],
        link: 'https://music.apple.com/ru/album/сектор-газа/601991162',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_1994_Танцы-После-Порева.png',
        album: 'Танцы После Порева',
        releasedAt: new Date('1994-06-01'),
        songs: [
            'Танцы После Порева',
            'Не Даёт',
            'Метаморфоза',
            'Вдова',
            'Проститутка',
            'Комары',
            'Незнакомые места',
            'Казачья',
            'Сельский Кайф',
            'Из чего же',
            'Богатые Тоже Плачут',
            'Укус Вампира',
            'Злая Ночь',
            'Вдова (Remix)',
        ],
        link: 'https://music.apple.com/ru/album/танцы-после-порева/601955301',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_1996_Газовая-атака.png',
        album: 'Газовая атака',
        releasedAt: new Date('1996-06-01'),
        songs: [
            'Аванс',
            'Свидание',
            'Вылазка',
            '30 лет',
            'Life',
            'Туман',
            'Твой звонок',
            'ГАИ',
            'Мак',
            'Чунга-Чанга',
            'Хата',
            'Рассказ, услышанный в автокомбинате',
            'Опарыш',
        ],
        link: 'https://music.apple.com/ru/album/газовая-атака/601953659',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc:
            '/albums/Sektor-gaza_1997_Наркологический-университет-миллионов.png',
        album: 'Наркологический университет миллионов',
        releasedAt: new Date('1997-05-01'),
        songs: [
            'Опять сегодня',
            'Кусок',
            'Новогодняя песня',
            'Песенка',
            'Похмел',
            'Самые лучшие тачки',
            'Марш наркоманов',
            'Свин',
            'Любовь раскумаренная',
            'Хорошо в деревне летом',
            'Пора домой',
            'Звёздная болезнь',
            'Вальпургиева ночь',
            'Песенка (remix)',
        ],
        link: 'https://music.apple.com/ru/album/наркологический-университет-миллионов/601956737',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_1993_Нажми-На-Газ.png',
        album: 'Нажми На Газ',
        releasedAt: new Date('1993-09-01'),
        songs: [
            'Нажми На Газ',
            'Кабак',
            'Подвал',
            'Девушка',
            'Суд',
            'Взял Вину На Себя',
            'Оборотень',
            'Мажор',
            'Лирика',
            'Дурак',
            'Тёща',
            'Мумия',
            'Репетиция',
            'Тёща (Remix)',
        ],
        link: 'https://music.apple.com/ru/album/нажми-на-газ/601960689',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_1991_Ночь-Перед-Рождеством.png',
        album: 'Ночь Перед Рождеством',
        releasedAt: new Date('1991-02-03'),
        songs: [
            'Привет, Ребята, Добрый День',
            'Ява',
            'Шары',
            'Давай-Давай',
            'Белая Горячка',
            'Голубь',
            'Презерватив',
            'Презерватив 2',
            'Щи',
            'Здравствуйте, Детишки',
            'Снегурочка',
            'Илья Муромец',
            'Кума',
            'Ночь Перед Рождеством',
            'Голубь (Remix)',
        ],
        link: 'https://music.apple.com/ru/album/ночь-перед-рождеством/601988863',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_1991_Колхозный-Панк.png',
        album: 'Колхозный Панк',
        releasedAt: new Date('1991-08-01'),
        songs: [
            'Queen',
            'Колхозный Панк',
            'Плуги-Вуги',
            'Патриот',
            'Наркоман',
            'Банка',
            'Попец',
            'Местные',
            'Утопленник',
            'Пасха',
            'Плуги-Вуги (Remix)',
        ],
        link: 'https://music.apple.com/ru/album/колхозный-панк/602776284',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_1990_Зловещие-Мертвецы.png',
        album: 'Зловещие Мертвецы',
        releasedAt: new Date('1990-05-20'),
        songs: [
            'Ой, Ты, Травушка Зелёная',
            'Сифон',
            'Ку-Ку',
            'Русский Мат',
            'Без Вина',
            'Голубой',
            'Страх',
            'Нас Ждут Из Темноты',
            'Вампиры',
            'Моя Смерть',
            'Когда Помрёшь',
            'Чёрная Магия',
            'Русский Мат (Remix)',
        ],
        link: 'https://music.apple.com/ru/album/зловещие-мертвецы/601989807',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_2000_Восставший-Из-Ада.png',
        album: 'Восставший Из Ада',
        releasedAt: new Date('2000-10-18'),
        songs: [
            'Демобилизация',
            'Свадьба',
            'Мои Рога - Моё Богатство (Рога)',
            'Сельский Туалет',
            'Грязная Кровь',
            'Любовь Загробная',
            'Чёрный Вурдалак',
            'Истребители Вампиров',
            'Сожженная Ведьма (Жертвам Средневековой Инквизиции Посвящается)',
            'Ночь Страха',
            'Мертвый В Доме',
            'Святая Война',
            'Восставший из ада',
        ],
        link: 'https://music.apple.com/ru/album/восставший-из-ада/601963927',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_2000_Восставший-Из-Ада.png',
        album: 'Гуляй, Мужик',
        releasedAt: new Date('1994-01-01'),
        songs: [
            'Гуляй, мужик!',
            'Мастурбация',
            'Видак',
            'Колхозная',
            'Я устал',
            'Л.Т.П.',
            'Бомж',
            'Трипак',
            'Як На Хуторе',
            'Вурдалак',
            'Моя бабка',
            'Частушки',
            'Видак (Remix)',
        ],
        link: 'https://music.apple.com/ru/album/гуляй-мужик/601957412',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_2015_Вой-на-Луну.png',
        album: 'Вой на Луну (лучшее и неизданное)',
        releasedAt: new Date('2015-11-13'),
        songs: [
            'Вступление (1981)',
            'Без вина (1981)',
            'Подруга шестиструнная',
            'Про лето',
            'Милая',
            'Первая любовь',
            'Проходят годы, словно миг',
            'Про мальчишку',
            'ЯВой на Луну',
            'Людмила',
            'Он так её любил',
            'Вампиры (1985)',
            'Заключительная',
            '30 лет',
            'Туман',
            'Пора домой',
            'Лирика',
            'Демобилизация',
            'Твой звонок',
            'Бомж',
            'Взял вину на себя',
            'Ночь перед Рождеством',
            'Life',
            'Вечером на лавочке',
            'Возле дома твоего',
            'Ява',
        ],
        link: 'https://music.apple.com/ru/album/вой-на-луну-лучшее-и-неизменное-deluxe-version/1057622388',
    },
    {
        band: Band.SEKTOR_GAZA,
        imageSrc: '/albums/Sektor-gaza_1994_Кащей-Бессмертный.png',
        album: 'Кащей Бессмертный',
        releasedAt: new Date('1994-06-01'),
        songs: [
            'Интродукция (Red Hot Chili Peppers — Fight Like a Brave)',
            'Ария Ивана (Red Hot Chili Peppers — Give It Away)',
            'Ария Ивана и Лягушки (Midi, Maxi & Efti — Go Girlie Go)',
            'Вторая ария Ивана',
            'Ария Бабы-Яги (Ace of Base — All That She Wants)',
            'Ария графа Дракулы (Anthrax — I Am the Law)',
            'Ария Василисы Прекрасной (Queen — Bohemian Rhapsody)',
            'Третья ария Ивана (AC/DC — You Shook Me All Night Long)',
            'Ария Кащея Бессмертного (Песняры — Дрозды)',
            'Четвёртая ария Ивана (Nirvana — Sliver)',
        ],
        link: '',
    },
] as const;

export const ALBUMS: AlbumType[] = [...albums].sort(
    (a, b) => a.releasedAt.getTime() - b.releasedAt.getTime(),
);
