export enum Band {
    BLACK_SABBATH = 'Black Sabbath',
    MANOWAR = 'Manowar',
    PANTERA = 'Pantera',
    RAINBOW = 'Rainbow',
    ELF = 'Elf',
    DIO = 'DIO',
    TESTAMENT = 'Testament',
    DAMAGEPLAN = 'Damageplan',
    AC_DC = 'AC/DC',
    SEPULTURA = 'Sepultura',
    KINO = 'Кино',
    ARIA = 'Ария',
    ACCEPT = 'Accept',
    SEKTOR_GAZA = 'Сектор Газа',
    CHERNIY_KOFE = 'Черный кофе',
    HEAVEN_AND_HELL = 'Heaven & Hell',
}
